language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv --version
  - pipenv install --system --deploy --ignore-pipfile
script:
  - flake8
  - pytest
  - coveralls
cache:
  directories:
    - "$PIP_CACHE_DIR"
    - "$PIPENV_CACHE_DIR"
env:
  - PIP_CACHE_DIR=$HOME/.cache/pip PIPENV_CACHE_DIR=$HOME/.cache/pipenv PIPENV_IGNORE_VIRTUALENVS=1
deploy:
  provider: heroku
  api_key:
    secure: 4oltk7DKJlrrtw6IrNZ6u+QF3d4aBlQUOZ7ac3KFlhWVLWp4l3VaUZdWP/RavcQ4RHUS1NYY11h7uPWU2YMCAidofRQNEKT2Ha3uheEvr3hBYqyApVc9nWCEM0Ew965X+JmC0zepxrwR7Q9rZRWbolKDVEBo7Cp444oeHM2zHfF7tDN70L3xR+BaK5wfavCVl4qe+1XJOkWGO6isb2ThmzBvIdUHNWPSKM+KRCKlaWfzTpqCmsbIqZTiEoIFG1u6rsRuw0x7PrPPlgPqyM5QCyLrN08jh8XqVtwjLOrFtL4k2IkFX9Mp36QoYuT5iq7ZE+h4Zm+y+OUikoN3Ph9ZEpH5VmGt4PXBogEdR+JtpT/XT6nTOLGbNxnPgLlGphKMukJ9LFQkRak+hlVzOTHT8PVLZrYtoPgtnnoR+hWg3iaRPUxdHyw7MZbFw5+X/NnIMFmM6je9363gczWcShUW3i8qTDxQ2lDsWpQV3xV6d3Lx3kIrGfQhiJavppgF39GqXNVfVgKaTEbQFZhIfgtB+/r0GJ/zxqpS9B7DXp5Jm0trgtshAsVKFpDA9hJ+AvFK4KI6kbO5CJ4OLjy/lKVb/XiWgg4+hXygLPSddUximhrDDT7Fl9Jh677I0jXcyVLOWsGJ8p7MBD0TWWSR5k758THgocNZZXB1Z+CeoRe2ee4=
  app: good-vacancy-backend
  on:
    repo: kosciak9/vacancy-backend
