language: python
dist: "xenial"
python:
  - "3.7"
install:
  - "pip install pipenv"
  - "pipenv --version"
  - "pipenv install --system --deploy --ignore-pipfile"
script:
  - "flake8"
  - "python ./manage.py test"
  - "coveralls"
cache:
  pip: true
