language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv --version
  - pipenv install --system --deploy --ignore-pipfile
script:
  - flake8
  - pytest
  - coveralls
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
env:
  - PIP_CACHE_DIR=$HOME/.cache/pip
  - PIPENV_CACHE_DIR=$HOME/.cache/pipenv

deploy:
  provider: heroku
  api_key:
    secure: wIfh3/W1JCGwhtAmNTyjkl1uE6Gc25sjdDKCE6tFggUVh03Jf86moSLd7Qnfn/i+/n/zmLkeGo1EdTQ1lst8KIQZ85ntmaQWMqSurgErKjvaadWw4XMqCQSQJewT0JTUB/YMxH/agrA94RFmrszxCPnKkh426gpXMKi4ixzwl67ni9phNB9Bwg/U3nqD8uSrLQSj0LfKb5dC7EDYXG0OZqL+AbiX3UHarDS/qSYdQ3GWlwQXZM9OdQbcOS1O0SD0aB6bDNaMcXlOy9uNXo209XF9Fmt0Bh+JCgqhZEn0cXfXitcM/LLc+Xz1Xa4y5yVVJSvRTMEtJr5HtQ0uye4GDw6DVuHEpGtAX5KdcJ8uDRm9TQYvxKCqIY5llYWD4qmAeYyDEYHYNUb1YNl2e8IY9kTy+95zwf/2l35WCevk0LGH2GpZnKV+8GWOCvcubwpvb09yScAhdIv+2E0jpJ2h8iRakGVfVJ63mcdSiIVgMilAca0YS3RYEjiIsUjfkNBFrIqlG8MixXu2UHcci02VDXkVNh24Q/EDyWQKzrrFRgcM+jh4phYNTs84kgQ316V6Oew0S2UsTH9jpezbwoA9/FMziR2tRGPdUAVjSFRuf/B7UCyXBuD1RuLMFiXbacAkrLSj3AbjxaiG1MQ0ueXXpxiTZglDTh2XbJzQTTl7xJw=
  app: good-vacancy-backend
  on:
    repo: kosciak9/vacancy-backend
