# Generated by Django 2.2.1 on 2019-05-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='additional_perks',
        ),
        migrations.AddField(
            model_name='position',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
        ),
        migrations.DeleteModel(
            name='AdditionalPerk',
        ),
    ]
